# Options and Settings

In [1]:
import pandas as pd

## Changing Options with Attributes
- The `pd.options` module configures Pandas's settings.
- The `display` module deals with the presentation of data.

In [4]:
spotify = pd.read_csv("spotify.csv")
spotify.head()

,Track,Artist,Album,Genre,Duration (min),Tempo (BPM),Energy,Danceability,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,R&B,3.74,105.4,0.5390,0.5747,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,R&B,3.82,76.9,0.4047,0.8809,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,Pop,3.04,130.7,0.6967,0.7497,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,Rock,3.35,156.7,0.8623,0.5503,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,Rock,2.77,153.5,0.7548,0.3262,-2.08,61,90.17

- The `max_rows` attribute sets the threshold/limit where the `DataFrame` rows will be truncated.
- The `min_rows` attribute sets the minimum number of displayed rows when `max_rows` is exceeded.
- Overwrite an attribute's value with an equal sign and the new value.

In [8]:
pd.options.display.max_rows
pd.options.display.min_rows

10

In [7]:
spotify

,Track,Artist,Album,Genre,Duration (min),Tempo (BPM),Energy,Danceability,Loudness (dB),Popularity,Streams (M)
0,Roads,The Midnight Drift,The Landscapes,R&B,3.74,105.4,0.5390,0.5747,-7.43,52,74.21
1,The Horizon of Nowhere,Starfall Collective,The Archives,R&B,3.82,76.9,0.4047,0.8809,-6.85,49,15.44
2,Sky Away,Sam Kariuki,Songs from the Underground,Pop,3.04,130.7,0.6967,0.7497,-6.25,67,253.67
3,Only Sunrise,Andre Laurent,The Territories,Rock,3.35,156.7,0.8623,0.5503,-8.31,72,10.00
4,Storm,The Broken Compass,The Chapters,Rock,2.77,153.5,0.7548,0.3262,-2.08,61,90.17
...,...,...,...,...,...,...,...,...,...,...,...
195,Waiting in the Sky,Nina Volkov,Chapters Vol. 2,Rock,3.73,152.4,0.9308,0.5013,-4.80,59,49.02
196,Waves Again,Luna Torres,Songs from the Edge of the World,Hip-Hop,2.88,67.6,0.7090,0.7991,-5.96,35,0.10
197,The Roads of Tomorrow,Sofia Vega,The Echoes,Rock,4.87,104.3,0.7052,0.4378,-1.00,84,930.03
198,Another Sunrise,The Wandering Suns,The Territories,Latin,2.60,118.6,0.7875,0.6610,-5.40,72,211.98
199,Silence Again,Luna Torres,Songs from the Edge of the World,Pop,4.64,103.4,0.7720,0.7726,-4.00,71,195.37

- The `max_columns` attribute sets the threshold/limit where the `DataFrame` columns will be truncated.

## Changing Options with Functions
- The `pd.get_option` function retrieves the current value for a pandas setting.
- The `pd.set_option` function sets a new value for a pandas setting.
- The `pd.describe_option` function provides documentation for a pandas setting.
- The `pd.reset_option` function returns a pandas setting back to its default value.

## The precision Option
- The `display.precision` option sets the number of digits that appears after a decimal point in a floating-point number.
- The default value is 6.

## Temporary Options with option_context
- The `pd.option_context` context manager temporarily changes options within a `with` block.
- Options revert back to their default values when the block ends.
- Pass a dictionary where the keys are the settings and the values are their temporary values.
- Use the `display` function to output the `DataFrame`.